### ISSUE TITLE
Problem enabling superguilds that doesn't load

### ISSUE THREAD

**Issue by Fargus-Van-Crystal-de-Mindark** [rplcnn/SuperGuilds#78]
# Welcome RepublicanSensei to this paste
# It is meant to provide you with better information about my problem

# We will start with some informational files
links.latest_log: https://hastebin.com/xovahuqoje

# Server Information
server.platform: bukkit
server.plugins: 
 - EasyCourt: 1.1.3
 - Repuska: 1.9
 - Combatant: 1.1.1
 - Lift: 56
 - Vehicles: 8.4
 - PlugMan: 2.1.3
 - RPGDrop: 1.7
 - SimpleAntiProxy: 0.6
 - DreamFish: Mysthoria
 - HPWizard: 1.2.11
 - MaintenanceMode: BETA 1.7
 - SimpleAPI: 3.5
 - Itemizer: 3.1.2
 - Timber: 1.1
 - Realistic-Swimming: 1.19.2
 - InvRestore2: 2.5.3
 - Modifyworld: 1.19.7
 - VehiclesFlags: 1.0
 - WitcheryX: 1.4
 - ActionBarAPI: 1.5.3
 - PremiumTurrets: 2.2.3
 - Multiverse-Core: 2.5.0-b727
 - RealisticFish: 2.0-beta
 - MCCore: 1.61
 - MVdWPlaceholderAPI: 1.0.0
 - FastAsyncWorldEdit: 17.07.12-6b6f285-750-13.7.8
 - PermissionsEx: 1.23.4
 - RPGHealthIndicator: 1.6
 - PEXPlayersRemover: 1.62
 - RPGFood: 1.5
 - TimeFold: 1.0
 - FastAsyncVoxelSniper: 17.05.15-b9c056c-695-12.8.9
 - PlaceholderAPI: 2.8.1
 - VarScript: 1.2.2
 - UltimateTs: 2.1.1
 - PorteCoulissante: 1.4.3
 - NametagEdit: 4.1.4
 - GeneralLib: 0.1.4
 - CompaniesManager: 2.0
 - RPGMiner: 1.0.1
 - TitleAPI: 1.7.5
 - VoxelSniper: 5.171.0-SNAPSHOT
 - EpicWorldGenerator: 7.2.29
 - Graves: 11
 - ParticleLIB: 2.1.1
 - PartySystem: 2.7
 - MOTD: 2.2
 - CoreProtect: 2.14.2
 - WorldEdit: 6.1.7-SNAPSHOT;3677-000c238
 - VoxelSniperGUI: 1.0.2
 - OpenInv: 3.2.1
 - Essentials: TeamCity
 - PlayerMention: 3.1
 - TreasureChest: 1.11
 - MysteryBoxes: 2.9.6
 - SQLibrary: 7.1
 - EffectLib: 5.4
 - Vault: 1.5.6-b49
 - ChairStairs: 1.1
 - MassiveCore: 2.12.1
 - CreativeGates: 2.12.1
 - StreetlightsAdvanced: 3.0.1
 - EssentialsGeoIP: TeamCity
 - GrowingOres: 2.3.4
 - AddLight: 4.1.5
 - MyCommand: 5.3.4
 - EpicNetherGenerator: 1.0.5
 - ServerTutorialPlus: 1.6.4
 - MessageAnnouncer: 1.8.0
 - Reporter: 3.2.7
 - Calendar: 1.7
 - EssentialsChat: TeamCity
 - SkillAPI: 3.1
 - SignColors: 1.1.1
 - EssentialsProtect: TeamCity
 - EssentialsAntiBuild: TeamCity
 - EssentialsSpawn: TeamCity
 - InfernalMobs: 5.2
 - AdvancedAchievements: 5.2.4
 - OpenAudioMc: 2.6
 - BKCommonLib: 1.12-v4
 - Train_Carts: 1.12-v2
 - TrainCartsOA: 1.0
 - RPGHorses: 1.5.1
 - HolographicDisplays: 2.2.6
 - Cinematic-Death: 1.0
 - RPGMobMoney: 1.6
 - RPGPlayerLeveling: 3.6
 - MythicMobs: 4.1.0-SNAPSHOT
 - Quests: 2.9.0-b140
 - Statz: 1.4.3
 - Skript: 2.2-dev29
 - SkAction: 2.0
 - LargeSk: 1.2-Beta
 - SkQuery: 3.21.4
 - WildSkript: 1.9
 - NPCDestinations_Animator: 2.6
 - SimplePets: 3.6.5
 - Citizens: 2.0.22-SNAPSHOT (build 1480)
 - NPC_Destinations: 2.1.11
 - NPC_Police: 2.0.29
 - CarlTheCreeper: 2.4.5
 - WorldGuard: 6.2.1;84bc322
 - ResourceGens: 2.1.3
 - WorldGuardExtraFlags: 2.3
 - Blacksmith: 1.1
 - ShopChest: 1.12.3
 - CommandNPC: 1.9.1
 - WorldGuardPushBack: 1.0
 - NavyCraft: 2.1.1-SNAPSHOT
 - Kingdoms: 13.2.30
 - Sentinel: 1.3.1 (build 119)
 - NPCDestinations_Farmer: 2.2
 - WGRegionEvents: S_Ryan
 - PirateSK: 0.4.1
 - Hotels: 1.1.1
 - ChatActions: 1.0
 - Skills: 10.0.5
 - Sentries: 2.1.3(build-b198)
 - ProtocolLib: 4.3.0
 - ChatItem: 1.3.5.6
 - WorldEditSelectionVisualizer: 1.4.7
 - skRayFall: 1.9.10
 - TransportPipes: 3.8.22
 - ChangeSkin: 2.3.2
 - LiteBans: 2.2.3
 - LibsDisguises: 9.4.0
 - RealVillagerTowns: 0.9
 - VanishNoPacket: 3.20
 - RPGInventory: 2.0.8
 - FactionMobs: 3.2.5_1.12-R0.1
 - DisguiseAbilities: 2.7.8

server.version: git-Spigot-8cbfc85-202da97 (MC: 1.12) / 1.12-R0.1-SNAPSHOT

# YAY! Now, let's see what we can find in my JVM
memory.free: 539081144
memory.max: 7635730432
java.specification.version: '1.8'
java.vendor: 'Oracle Corporation'
java.version: '1.8.0_111'
os.arch: 'amd64'
os.name: 'Linux'
os.version: '3.14.32-xxxx-std-ipv6-64'

# Okay :D Great. You are now ready to study all of this! Has you can see there is a lot of errors about superguilds and I don't understand what is worng... maybe you can understand it and give me help ?

Thanks in advance

Fargus

**Comment by rplcnn** [comment]
You can delete SUPERGUILDS_wars for now because its working on progress.

For other error I found a solution and will update guilds today.

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
Thanks a lot

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
Now /g it is showed but there are still problems... it give me (none) message.

https://hastebin.com/pugesifuca

Please to reads the latest logs

**Comment by rplcnn** [comment]
I know this bug. Repuska doesn't support skript versions higher than republicansensei.com's one. I will fix this.

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
thanks I will wait for yout next update

**Comment by rplcnn** [comment]
Fixed your skquery issue. Update your guilds

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
The problem has not solved.

I had obliged to remove your new repulska... it didn't let me start the server at all... 
Do you test your plugins before to put it in download?

**Comment by rplcnn** [comment]
Yeah, i tested and didn't see any problem in lastest spigot
